schema_version: 1

# Run with Gunicorn (Flask WSGI). Uses Databricks-provided port env; falls back to 3000 locally.
command:
  - gunicorn
  - "-b"
  - "0.0.0.0:${DATABRICKS_APP_PORT:-3000}"
  - "approot.app:app"
  - "-w"
  - "2"

# Extra environment variables (Secrets are injected by Databricks Apps)
env:
  - name: SQLALCHEMY_DATABASE_URL
    value: "{{secrets/app-secrets/sqlalchemy_database_url}}"
  - name: DB_POOL_SIZE
    value: "5"
  - name: DB_MAX_OVERFLOW
    value: "10"
  - name: DB_POOL_TIMEOUT
    value: "30"
  - name: DATABRICKS_OAUTH_SCOPE
    value: "{{secrets/app-secrets/oauth_scope}}"

# Install Python dependencies from the bundled requirements file
python:
  pip_requirements_file: approot/requirements.txt
